### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by SkarletShadows** [ferriarnus/Unidentified-Enchantments#17]
## Information
Forge version: 41.0.87
Minecraft: 1.19
## Logs
    -- MOD unidentifiedenchantments --
    Details:
	    Caused by 0: java.lang.reflect.InvocationTargetException
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/common/loot/GlobalLootModifierSerializer
		    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
		    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
		    at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
		    at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		    at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		    at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		    at com.ferri.arnus.unidentifiedenchantments.loot.LootRegistry.<clinit>(LootRegistry.java:19) ~[unidentifiedenchantments-1.0.11.jar%23159!/:1.0.11] {re:classloading}
		    at com.ferri.arnus.unidentifiedenchantments.UnidentifiedEnchantments.<init>(UnidentifiedEnchantments.java:36) ~[unidentifiedenchantments-1.0.11.jar%23159!/:1.0.11] {re:classloading}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Mod File: unidentifiedenchantments-1.0.11.jar
	    Failure message: Unidentified Enchantments (unidentifiedenchantments) has failed to load correctly
		    java.lang.reflect.InvocationTargetException: null
	    Mod Version: 1.0.11
	    Mod Issue URL: NOT PROVIDED
	    Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.loot.GlobalLootModifierSerializer
    Stacktrace:
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	    at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
	    at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	    at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	    at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	    at com.ferri.arnus.unidentifiedenchantments.loot.LootRegistry.<clinit>(LootRegistry.java:19) ~[unidentifiedenchantments-1.0.11.jar%23159!/:1.0.11] {re:classloading}
	    at com.ferri.arnus.unidentifiedenchantments.UnidentifiedEnchantments.<init>(UnidentifiedEnchantments.java:36) ~[unidentifiedenchantments-1.0.11.jar%23159!/:1.0.11] {re:classloading}
	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by SkarletShadows** [comment]
The forge version was too high, I apologize!

**Comment by ferriarnus** [comment]
Yeah forge made a change to how glm work. I will have a look at it in a bit.
